# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            资料分享
tagline:          'A Jekyll theme'
description:      '<a href="https://cat-zhaocai.github.io/share/" target="_blank">招财猫的资料分享站</a>'
url:              https://cat-zhaocai.github.io
baseurl:          '/share'
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'cat-zhaocai'
  url:            https://cat-zhaocai.github.io/share/

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
